config/routes.rb
Rails.application.routes.draw do
  resources :boards do
    resources :comments, only: [:create, :destroy]
  end

  root to: "boards#index"
end

app/models/board.rb
class Board < ActiveRecord::Base
  validates :title, presence: true, length: { in: 4..127 }
  validates :editor, presence: true, length: { in: 1..30 }

  has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :board

  validates :board, presence: true
  validates :content, presence: true, length: { in: 1..127}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    @boards = Board.includes(:comments).all
  end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(params_board)
    if @board.save
      redirect_to boards_path
    else
      render "new"
    end
  end

  def show
    @board = Board.includes(:comments).find(params[:id])
    @comment = Comment.new

  end

  def edit
    @board = Board.find(params[:id])
  end

  def update
    @board = Board.find(params[:id])
    if @board.update_attributes(params_board)
      redirect_to board_path(@board)
    else
      render "edit"
    end
  end

  def destroy
    @board = Board.find(params[:id])
    @board.destroy
    redirect_to boards_path
  end

  private

  def params_board
    params.require(:board).permit(:title, :editor)
  end
end

app/controllers/concerns/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @board = Board.find(params[:board_id])
    @comment = Comment.new(params_comment)
    @comment.board = @board

    if @comment.save
      redirect_to board_url(@board)
    else
      render "boards/show"
    end
  end

  def destroy
    @board = Board.find(params[:board_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to board_path(@board)
  end

  private

  def params_comment
    params.require(:comment).permit(:name, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/edit.html.erb
this is edit.erb
<p> <%= link_to "topへ戻る", boards_path %> </p>

<% if @board.errors.any? %>
 <%= @board.errors.full_messages %>
<% end %>
<%= form_for @board do |f| %>
  <%= f.text_field :title %>
  <%= f.text_field :editor %>
  <%= f.submit %>
<% end %>

app/views/boards/index.html.erb
<div class="keijiban__header">
  <div class="header__top">
    <div class="top__word">掲示板</div>
  </div>
  <div class="header__diviver"></div>
  <div class="header__bottom">
    <div class="bottom__icons">
      <%= link_to new_board_path(@board), class: "icons__icon" do %>
        <i class="fa fa-pencil"></i>
      <% end %>
      <%= link_to boards_path, class: "icons__icon" do %>
        <i class="fa fa-book"></i>
      <% end %>
      <i class="icons__icon fa fa-group"></i>
      <i class="icons__icon fa fa-sign-in"></i>
    </div>
  </div>
  <div class="keijiban__search">
    <input class="fa search__form container" placeholder="&#xf002; 名前で検索">
  </div>
</div>
<div class="keijiban__body">
  <div class="keijiban__courses">
    <div class="courses__header">
      <div class="header__word">
        掲示板数(<%= @boards.size %>)
      </div>
    </div>
    <div class="courses__body">
      <% @boards.each do |board| %>
        <%= link_to  "/boards/#{board.id}", target: "_blank" do %>
          <div class="body__course">
            <div class="course__img">
            </div>
            <div class="course__content">
              <%= board.title %>
              <span class="content__cm-count">
                <%= board.comments.size %>
              </span>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<!-- <h1>2chクローン</h1>

<%= link_to "新規作成する", new_board_path(@board) %>
<hr>
<%= @boards.size %>
<% @boards.each do |board| %>
  <p>タイトル： <%= link_to "#{board.title}", "/boards/#{board.id}" %></p>
  <p>作者：<%= board.editor %></p>
<% end %> -->

app/views/boards/new.html.erb
<%= link_to "スレッドに戻る", boards_path %>

<hr>

<h1>Boards#new</h1>
<% if @board.errors.any? %>
  <%= @board.errors.full_messages %>
<% end %>
<%= form_for @board do |f|%>
  タイトル: <%= f.text_field :title %><br>
  作成者名：<%= f.text_field :editor %><br>
  <%= f.submit %>
<% end %>

app/views/boards/show.html.erb
<div class="keijiban-show">
  <div class="keijiban__header">
    <div class="header__top">
      <div class="top__word">
        <%= link_to board_path(@board), method: :delete, data: {confirm: "削除しますか？"} do%>
          <%= @board.title %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="keijiban__body keijiban__body--show">
    <div class="keijiban__cm-content">
      <% @board.comments.each do |comment|  %>
        <div class="cm-content__comment">

          <div class="comment__content">
            <div class="content__img">
              <%= image_tag("apple.jpg") %>
            </div>
            <div class="content__name">
              <%= comment.name %>
            </div>
            <%= link_to board_comment_path(@board, comment), method: :delete, data: {confirm: "削除しますか？"} do%>
              <div class="content__text">
                <%= comment.content %>
                <div class="content__time">
                  <%= (comment.created_at + 9.hour).strftime("%H:%M") %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="keijiban__cm-footer">
      <%= form_for @comment, url: board_comments_path(@board, @comment) do |f| %>
        <%= f.text_area :content, class: "cm-footer__form" %>
        <%= f.submit value: "送信", class: "cm-footer__submit" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Keijiban1130</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta charset="UTF-8">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>